// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/smoug25/tensorflow_serving_helper/tensorflow_serving/config/log_collector_config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogCollectorConfig struct {
	// Identifies the type of the LogCollector we will use to collect these logs.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The prefix to use for the filenames of the logs.
	FilenamePrefix       string   `protobuf:"bytes,2,opt,name=filename_prefix,json=filenamePrefix,proto3" json:"filename_prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogCollectorConfig) Reset()         { *m = LogCollectorConfig{} }
func (m *LogCollectorConfig) String() string { return proto.CompactTextString(m) }
func (*LogCollectorConfig) ProtoMessage()    {}
func (*LogCollectorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a1b742bdf4d8a06, []int{0}
}

func (m *LogCollectorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogCollectorConfig.Unmarshal(m, b)
}
func (m *LogCollectorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogCollectorConfig.Marshal(b, m, deterministic)
}
func (m *LogCollectorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogCollectorConfig.Merge(m, src)
}
func (m *LogCollectorConfig) XXX_Size() int {
	return xxx_messageInfo_LogCollectorConfig.Size(m)
}
func (m *LogCollectorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_LogCollectorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_LogCollectorConfig proto.InternalMessageInfo

func (m *LogCollectorConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LogCollectorConfig) GetFilenamePrefix() string {
	if m != nil {
		return m.FilenamePrefix
	}
	return ""
}

func init() {
	proto.RegisterType((*LogCollectorConfig)(nil), "tensorflow.serving.LogCollectorConfig")
}

func init() {
	proto.RegisterFile("github.com/smoug25/tensorflow_serving_helper/tensorflow_serving/config/log_collector_config.proto", fileDescriptor_1a1b742bdf4d8a06)
}

var fileDescriptor_1a1b742bdf4d8a06 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x4a, 0x4c, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0xce, 0xcd, 0x2f, 0x4d, 0x37, 0x32, 0xd5, 0x2f,
	0x49, 0xcd, 0x2b, 0xce, 0x2f, 0x4a, 0xcb, 0xc9, 0x2f, 0x8f, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0xcc,
	0x4b, 0x8f, 0xcf, 0x48, 0xcd, 0x29, 0x48, 0x2d, 0xc2, 0x22, 0xa3, 0x9f, 0x9c, 0x9f, 0x97, 0x96,
	0x99, 0xae, 0x9f, 0x93, 0x9f, 0x1e, 0x9f, 0x9c, 0x9f, 0x93, 0x93, 0x9a, 0x5c, 0x92, 0x5f, 0x14,
	0x0f, 0x11, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x42, 0xe8, 0xd2, 0x83, 0xea, 0x52,
	0x0a, 0xe4, 0x12, 0xf2, 0xc9, 0x4f, 0x77, 0x86, 0x69, 0x70, 0x06, 0xab, 0x17, 0x12, 0xe2, 0x62,
	0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xd4, 0xb9,
	0xf8, 0xd3, 0x32, 0x73, 0x52, 0xf3, 0x12, 0x73, 0x53, 0xe3, 0x0b, 0x8a, 0x52, 0xd3, 0x32, 0x2b,
	0x24, 0x98, 0xc0, 0xd2, 0x7c, 0x30, 0xe1, 0x00, 0xb0, 0xa8, 0x93, 0x77, 0x94, 0x1b, 0x75, 0xfc,
	0xf2, 0x83, 0x91, 0x31, 0x89, 0x0d, 0xec, 0x74, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe0,
	0xf5, 0xee, 0xf6, 0x1f, 0x01, 0x00, 0x00,
}
