// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/smoug25/tensorflow_serving_helper/tensorflow_serving/config/platform_config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Configuration for a servable platform e.g. tensorflow or other ML systems.
type PlatformConfig struct {
	// The config proto for a SourceAdapter in the StoragePathSourceAdapter
	// registry.
	SourceAdapterConfig  *any.Any `protobuf:"bytes,1,opt,name=source_adapter_config,json=sourceAdapterConfig,proto3" json:"source_adapter_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatformConfig) Reset()         { *m = PlatformConfig{} }
func (m *PlatformConfig) String() string { return proto.CompactTextString(m) }
func (*PlatformConfig) ProtoMessage()    {}
func (*PlatformConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a70a0852932f345, []int{0}
}

func (m *PlatformConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformConfig.Unmarshal(m, b)
}
func (m *PlatformConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformConfig.Marshal(b, m, deterministic)
}
func (m *PlatformConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformConfig.Merge(m, src)
}
func (m *PlatformConfig) XXX_Size() int {
	return xxx_messageInfo_PlatformConfig.Size(m)
}
func (m *PlatformConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformConfig proto.InternalMessageInfo

func (m *PlatformConfig) GetSourceAdapterConfig() *any.Any {
	if m != nil {
		return m.SourceAdapterConfig
	}
	return nil
}

type PlatformConfigMap struct {
	// A map from a platform name to a platform config. The platform name is used
	// in ModelConfig.model_platform.
	PlatformConfigs      map[string]*PlatformConfig `protobuf:"bytes,1,rep,name=platform_configs,json=platformConfigs,proto3" json:"platform_configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PlatformConfigMap) Reset()         { *m = PlatformConfigMap{} }
func (m *PlatformConfigMap) String() string { return proto.CompactTextString(m) }
func (*PlatformConfigMap) ProtoMessage()    {}
func (*PlatformConfigMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a70a0852932f345, []int{1}
}

func (m *PlatformConfigMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformConfigMap.Unmarshal(m, b)
}
func (m *PlatformConfigMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformConfigMap.Marshal(b, m, deterministic)
}
func (m *PlatformConfigMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformConfigMap.Merge(m, src)
}
func (m *PlatformConfigMap) XXX_Size() int {
	return xxx_messageInfo_PlatformConfigMap.Size(m)
}
func (m *PlatformConfigMap) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformConfigMap.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformConfigMap proto.InternalMessageInfo

func (m *PlatformConfigMap) GetPlatformConfigs() map[string]*PlatformConfig {
	if m != nil {
		return m.PlatformConfigs
	}
	return nil
}

func init() {
	proto.RegisterType((*PlatformConfig)(nil), "tensorflow.serving.PlatformConfig")
	proto.RegisterType((*PlatformConfigMap)(nil), "tensorflow.serving.PlatformConfigMap")
	proto.RegisterMapType((map[string]*PlatformConfig)(nil), "tensorflow.serving.PlatformConfigMap.PlatformConfigsEntry")
}

func init() {
	proto.RegisterFile("github.com/smoug25/tensorflow_serving_helper/tensorflow_serving/config/platform_config.proto", fileDescriptor_9a70a0852932f345)
}

var fileDescriptor_9a70a0852932f345 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xc9, 0x86, 0x82, 0x19, 0xe8, 0x8c, 0x13, 0xea, 0x4e, 0xa3, 0xa7, 0x9d, 0x12, 0xa8,
	0x08, 0x63, 0xb7, 0x29, 0x8a, 0x20, 0x82, 0xf4, 0x38, 0x84, 0x92, 0xd6, 0x34, 0x2b, 0xb6, 0x79,
	0x43, 0x92, 0x4e, 0xfa, 0x75, 0xfd, 0x14, 0x1e, 0xc5, 0xa6, 0x22, 0xfb, 0x03, 0x5e, 0x76, 0x6b,
	0xdf, 0x3c, 0xbf, 0x1f, 0xcf, 0x9b, 0xe0, 0x57, 0x59, 0xb8, 0x55, 0x9d, 0xd2, 0x0c, 0x2a, 0x66,
	0x2b, 0xa8, 0x65, 0x74, 0xc3, 0x9c, 0x50, 0x16, 0x4c, 0x5e, 0xc2, 0x47, 0x62, 0x85, 0x59, 0x17,
	0x4a, 0x26, 0x2b, 0x51, 0x6a, 0x61, 0xf6, 0x9c, 0xb0, 0x0c, 0x54, 0x5e, 0x48, 0xa6, 0x4b, 0xee,
	0x72, 0x30, 0x55, 0xe2, 0xff, 0xa9, 0x36, 0xe0, 0x80, 0x90, 0x3f, 0x80, 0x76, 0xc0, 0xf8, 0x4a,
	0x02, 0xc8, 0x52, 0xb0, 0x36, 0x91, 0xd6, 0x39, 0xe3, 0xaa, 0xf1, 0xf1, 0x70, 0x89, 0x4f, 0x5f,
	0x3a, 0xcf, 0x5d, 0xab, 0x21, 0x8f, 0xf8, 0xd2, 0x42, 0x6d, 0x32, 0x91, 0xf0, 0x37, 0xae, 0x9d,
	0x30, 0x9d, 0x3f, 0x40, 0x13, 0x34, 0x1d, 0x44, 0x23, 0xea, 0x65, 0xf4, 0x57, 0x46, 0x17, 0xaa,
	0x89, 0x2f, 0x3c, 0xb2, 0xf0, 0x84, 0x37, 0x85, 0x9f, 0x08, 0x9f, 0x6f, 0xca, 0x9f, 0xb9, 0x26,
	0x02, 0x0f, 0xb7, 0x9a, 0xdb, 0x00, 0x4d, 0xfa, 0xd3, 0x41, 0x34, 0xa7, 0xbb, 0xdd, 0xe9, 0x8e,
	0x60, 0x6b, 0x62, 0xef, 0x95, 0x33, 0x4d, 0x7c, 0xa6, 0x37, 0xa7, 0xe3, 0x1c, 0x8f, 0xf6, 0x05,
	0xc9, 0x10, 0xf7, 0xdf, 0x45, 0xd3, 0x2e, 0x73, 0x12, 0xff, 0x7c, 0x92, 0x19, 0x3e, 0x5a, 0xf3,
	0xb2, 0x16, 0x41, 0xaf, 0x5d, 0x30, 0xfc, 0xbf, 0x45, 0xec, 0x81, 0x79, 0x6f, 0x86, 0x6e, 0x9f,
	0x96, 0x0f, 0x87, 0x79, 0xcf, 0x2f, 0x84, 0xd2, 0xe3, 0xf6, 0x52, 0xaf, 0xbf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x45, 0x14, 0xb8, 0x48, 0x23, 0x02, 0x00, 0x00,
}
