// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/smoug25/tensorflow_serving_helper/tensorflow/core/protobuf/conv_autotuning.proto

package tensorflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	stream_executor "github.com/smoug25/tensorflow_serving_helper/tensorflow/stream_executor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A convolution. Currently it's only used for logging. In the future, we may
// want to use it in the API as well.
type ConvolutionProto struct {
	Kind     stream_executor.ConvolutionKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=stream_executor.dnn.ConvolutionKind" json:"kind,omitempty"`
	Input    *stream_executor.TensorDescriptorProto      `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Filter   *stream_executor.TensorDescriptorProto      `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Output   *stream_executor.TensorDescriptorProto      `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	ConvDesc *stream_executor.ConvolutionDescriptorProto `protobuf:"bytes,5,opt,name=conv_desc,json=convDesc,proto3" json:"conv_desc,omitempty"`
	// result = conv_scale * conv(...) + side_value_scale * side_value.
	// side_value is an arbitrary buffer if activation is not none. Otherwise, it
	// has to be the result buffer (using its old values).
	ConvScale            float64                        `protobuf:"fixed64,6,opt,name=conv_scale,json=convScale,proto3" json:"conv_scale,omitempty"`
	SideValueScale       float64                        `protobuf:"fixed64,7,opt,name=side_value_scale,json=sideValueScale,proto3" json:"side_value_scale,omitempty"`
	Activation           stream_executor.ActivationMode `protobuf:"varint,8,opt,name=activation,proto3,enum=stream_executor.dnn.ActivationMode" json:"activation,omitempty"`
	InputAddress         int64                          `protobuf:"varint,9,opt,name=input_address,json=inputAddress,proto3" json:"input_address,omitempty"`
	FilterAddress        int64                          `protobuf:"varint,10,opt,name=filter_address,json=filterAddress,proto3" json:"filter_address,omitempty"`
	OutputAddress        int64                          `protobuf:"varint,11,opt,name=output_address,json=outputAddress,proto3" json:"output_address,omitempty"`
	BiasAddress          int64                          `protobuf:"varint,12,opt,name=bias_address,json=biasAddress,proto3" json:"bias_address,omitempty"`
	SideInputAddress     int64                          `protobuf:"varint,13,opt,name=side_input_address,json=sideInputAddress,proto3" json:"side_input_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ConvolutionProto) Reset()         { *m = ConvolutionProto{} }
func (m *ConvolutionProto) String() string { return proto.CompactTextString(m) }
func (*ConvolutionProto) ProtoMessage()    {}
func (*ConvolutionProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_72cd4d662bd3ed86, []int{0}
}

func (m *ConvolutionProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvolutionProto.Unmarshal(m, b)
}
func (m *ConvolutionProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvolutionProto.Marshal(b, m, deterministic)
}
func (m *ConvolutionProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvolutionProto.Merge(m, src)
}
func (m *ConvolutionProto) XXX_Size() int {
	return xxx_messageInfo_ConvolutionProto.Size(m)
}
func (m *ConvolutionProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvolutionProto.DiscardUnknown(m)
}

var xxx_messageInfo_ConvolutionProto proto.InternalMessageInfo

func (m *ConvolutionProto) GetKind() stream_executor.ConvolutionKind {
	if m != nil {
		return m.Kind
	}
	return stream_executor.ConvolutionKind_INVALID
}

func (m *ConvolutionProto) GetInput() *stream_executor.TensorDescriptorProto {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *ConvolutionProto) GetFilter() *stream_executor.TensorDescriptorProto {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ConvolutionProto) GetOutput() *stream_executor.TensorDescriptorProto {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *ConvolutionProto) GetConvDesc() *stream_executor.ConvolutionDescriptorProto {
	if m != nil {
		return m.ConvDesc
	}
	return nil
}

func (m *ConvolutionProto) GetConvScale() float64 {
	if m != nil {
		return m.ConvScale
	}
	return 0
}

func (m *ConvolutionProto) GetSideValueScale() float64 {
	if m != nil {
		return m.SideValueScale
	}
	return 0
}

func (m *ConvolutionProto) GetActivation() stream_executor.ActivationMode {
	if m != nil {
		return m.Activation
	}
	return stream_executor.ActivationMode_kNone
}

func (m *ConvolutionProto) GetInputAddress() int64 {
	if m != nil {
		return m.InputAddress
	}
	return 0
}

func (m *ConvolutionProto) GetFilterAddress() int64 {
	if m != nil {
		return m.FilterAddress
	}
	return 0
}

func (m *ConvolutionProto) GetOutputAddress() int64 {
	if m != nil {
		return m.OutputAddress
	}
	return 0
}

func (m *ConvolutionProto) GetBiasAddress() int64 {
	if m != nil {
		return m.BiasAddress
	}
	return 0
}

func (m *ConvolutionProto) GetSideInputAddress() int64 {
	if m != nil {
		return m.SideInputAddress
	}
	return 0
}

func init() {
	proto.RegisterType((*ConvolutionProto)(nil), "tensorflow.ConvolutionProto")
}

func init() {
	proto.RegisterFile("github.com/smoug25/tensorflow_serving_helper/tensorflow/core/protobuf/conv_autotuning.proto", fileDescriptor_72cd4d662bd3ed86)
}

var fileDescriptor_72cd4d662bd3ed86 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x5f, 0x6b, 0xd4, 0x40,
	0x14, 0xc5, 0x89, 0xed, 0xae, 0xed, 0xdd, 0x3f, 0x94, 0x79, 0x0a, 0x82, 0xb0, 0x5a, 0x85, 0x20,
	0xb2, 0x81, 0x15, 0xc1, 0x47, 0x6b, 0x7d, 0x11, 0x15, 0x34, 0x8a, 0x2f, 0x3e, 0x84, 0xec, 0xcc,
	0xdd, 0xed, 0x60, 0x76, 0xee, 0x32, 0x7f, 0xa2, 0x9f, 0xcc, 0xcf, 0x27, 0x73, 0xa7, 0x8d, 0xb1,
	0x14, 0xa4, 0x7d, 0x3d, 0xf9, 0x9d, 0x73, 0x0f, 0x67, 0x02, 0xdf, 0xb7, 0xda, 0x5f, 0x84, 0xf5,
	0x52, 0xd2, 0xae, 0x74, 0x3b, 0x0a, 0xdb, 0xd5, 0xcb, 0xd2, 0xa3, 0x71, 0x64, 0x37, 0x2d, 0xfd,
	0xac, 0x1d, 0xda, 0x4e, 0x9b, 0x6d, 0x7d, 0x81, 0xed, 0x1e, 0xed, 0xe0, 0x4b, 0x29, 0xc9, 0x62,
	0xb9, 0xb7, 0xe4, 0x69, 0x1d, 0x36, 0xa5, 0x24, 0xd3, 0xd5, 0x4d, 0xf0, 0xe4, 0x83, 0xd1, 0x66,
	0xbb, 0xe4, 0x0f, 0x02, 0xfe, 0xf2, 0x0f, 0x3e, 0xdf, 0xf5, 0x90, 0xf3, 0x16, 0x9b, 0x5d, 0x8d,
	0xbf, 0x50, 0x06, 0x4f, 0xb6, 0x54, 0xc6, 0xa4, 0xf8, 0xc7, 0xbf, 0x47, 0x70, 0x72, 0x4e, 0xa6,
	0xa3, 0x36, 0x78, 0x4d, 0xe6, 0x13, 0xdf, 0x7c, 0x05, 0x87, 0x3f, 0xb4, 0x51, 0x79, 0xb6, 0xc8,
	0x8a, 0xf9, 0xea, 0xc9, 0xf2, 0x9a, 0x7d, 0x19, 0xed, 0x03, 0xd3, 0x7b, 0x6d, 0x54, 0xc5, 0x0e,
	0xf1, 0x1a, 0x46, 0xda, 0xec, 0x83, 0xcf, 0xef, 0x2d, 0xb2, 0x62, 0xb2, 0x7a, 0x76, 0xa3, 0xf5,
	0x2b, 0x17, 0x7b, 0x8b, 0x4e, 0x5a, 0xbd, 0xf7, 0x64, 0xf9, 0x68, 0x95, 0x8c, 0xe2, 0x0d, 0x8c,
	0x37, 0xba, 0xf5, 0x68, 0xf3, 0x83, 0x5b, 0x47, 0x5c, 0x3a, 0x63, 0x06, 0x05, 0x1f, 0x6b, 0x1c,
	0xde, 0x3e, 0x23, 0x39, 0xc5, 0x07, 0x38, 0xe6, 0x07, 0x51, 0xe8, 0x64, 0x3e, 0xe2, 0x98, 0xf2,
	0x7f, 0x43, 0x5c, 0xcf, 0x3a, 0x8a, 0x09, 0x51, 0x14, 0x0f, 0x01, 0x38, 0xcd, 0xc9, 0xa6, 0xc5,
	0x7c, 0xbc, 0xc8, 0x8a, 0xac, 0xe2, 0xfc, 0x2f, 0x51, 0x10, 0x05, 0x9c, 0x38, 0xad, 0xb0, 0xee,
	0x9a, 0x36, 0xe0, 0x25, 0x74, 0x9f, 0xa1, 0x79, 0xd4, 0xbf, 0x45, 0x39, 0x91, 0xe7, 0x00, 0x8d,
	0xf4, 0xba, 0x6b, 0xe2, 0xbd, 0xfc, 0x88, 0x1f, 0xe8, 0xf4, 0xc6, 0x5e, 0x67, 0x3d, 0xf6, 0x91,
	0x14, 0x56, 0x03, 0x9b, 0x38, 0x85, 0x19, 0x8f, 0x5d, 0x37, 0x4a, 0x59, 0x74, 0x2e, 0x3f, 0x5e,
	0x64, 0xc5, 0x41, 0x35, 0x65, 0xf1, 0x2c, 0x69, 0xe2, 0x29, 0xcc, 0xd3, 0x9c, 0x3d, 0x05, 0x4c,
	0xcd, 0x92, 0x3a, 0xc0, 0xd2, 0x62, 0x3d, 0x36, 0x49, 0x58, 0x52, 0xaf, 0xb0, 0x47, 0x30, 0x5d,
	0xeb, 0xc6, 0xf5, 0xd0, 0x94, 0xa1, 0x49, 0xd4, 0xae, 0x90, 0xe7, 0x20, 0x78, 0x84, 0x7f, 0xab,
	0xcd, 0x18, 0xe4, 0x79, 0xde, 0x0d, 0xea, 0xad, 0xc7, 0xfc, 0xff, 0xbe, 0xf8, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x9d, 0x2b, 0xd0, 0x0d, 0x7d, 0x03, 0x00, 0x00,
}
