// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/tensorflow_server.proto

package tensorflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Defines the configuration of a single TensorFlow server.
type ServerDef struct {
	// The cluster of which this server is a member.
	Cluster *ClusterDef `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// The name of the job of which this server is a member.
	//
	// NOTE(mrry): The `cluster` field must contain a `JobDef` with a `name` field
	// that matches this name.
	JobName string `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	// The task index of this server in its job.
	//
	// NOTE: The `cluster` field must contain a `JobDef` with a matching `name`
	// and a mapping in its `tasks` field for this index.
	TaskIndex int32 `protobuf:"varint,3,opt,name=task_index,json=taskIndex,proto3" json:"task_index,omitempty"`
	// The default configuration for sessions that run on this server.
	DefaultSessionConfig *ConfigProto `protobuf:"bytes,4,opt,name=default_session_config,json=defaultSessionConfig,proto3" json:"default_session_config,omitempty"`
	// The protocol to be used by this server.
	//
	// Acceptable values include: "grpc", "grpc+verbs".
	Protocol string `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// The server port. If not set, then we identify the port from the job_name.
	Port                 int32    `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerDef) Reset()         { *m = ServerDef{} }
func (m *ServerDef) String() string { return proto.CompactTextString(m) }
func (*ServerDef) ProtoMessage()    {}
func (*ServerDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f0f8cbd85b669e4, []int{0}
}

func (m *ServerDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerDef.Unmarshal(m, b)
}
func (m *ServerDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerDef.Marshal(b, m, deterministic)
}
func (m *ServerDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerDef.Merge(m, src)
}
func (m *ServerDef) XXX_Size() int {
	return xxx_messageInfo_ServerDef.Size(m)
}
func (m *ServerDef) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerDef.DiscardUnknown(m)
}

var xxx_messageInfo_ServerDef proto.InternalMessageInfo

func (m *ServerDef) GetCluster() *ClusterDef {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *ServerDef) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *ServerDef) GetTaskIndex() int32 {
	if m != nil {
		return m.TaskIndex
	}
	return 0
}

func (m *ServerDef) GetDefaultSessionConfig() *ConfigProto {
	if m != nil {
		return m.DefaultSessionConfig
	}
	return nil
}

func (m *ServerDef) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *ServerDef) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*ServerDef)(nil), "tensorflow.ServerDef")
}

func init() {
	proto.RegisterFile("tensorflow/core/protobuf/tensorflow_server.proto", fileDescriptor_7f0f8cbd85b669e4)
}

var fileDescriptor_7f0f8cbd85b669e4 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcb, 0x4e, 0xeb, 0x30,
	0x10, 0x86, 0xe5, 0x73, 0x7a, 0x1d, 0x58, 0x59, 0xa8, 0x98, 0x48, 0x48, 0x15, 0x12, 0x28, 0xab,
	0xa4, 0x82, 0x37, 0x28, 0xdd, 0xb0, 0x00, 0x55, 0xe9, 0x03, 0x44, 0xb9, 0x8c, 0xab, 0x94, 0xc4,
	0x53, 0xd9, 0x0e, 0xf0, 0xe4, 0x88, 0x25, 0x8a, 0xdd, 0x12, 0x58, 0x74, 0x97, 0xcc, 0x37, 0xff,
	0x65, 0x0c, 0x0b, 0x8b, 0xca, 0x90, 0x96, 0x35, 0xbd, 0xc7, 0x05, 0x69, 0x8c, 0xf7, 0x9a, 0x2c,
	0xe5, 0xad, 0x8c, 0x7b, 0x90, 0x1a, 0xd4, 0x6f, 0xa8, 0x23, 0x87, 0x38, 0xf4, 0x20, 0xb8, 0x3d,
	0xa9, 0x2e, 0x48, 0xc9, 0x6a, 0xeb, 0x25, 0xc1, 0xdd, 0xe9, 0xb5, 0xba, 0x35, 0xf6, 0x68, 0x7d,
	0xf3, 0xc9, 0x60, 0xba, 0x71, 0x59, 0x2b, 0x94, 0x7c, 0x01, 0xe3, 0x03, 0x16, 0x6c, 0xce, 0xc2,
	0xb3, 0xfb, 0x59, 0xd4, 0xfb, 0x44, 0x8f, 0x1e, 0xad, 0x50, 0x26, 0xc7, 0x35, 0x7e, 0x05, 0x93,
	0x1d, 0xe5, 0xa9, 0xca, 0x1a, 0x14, 0xff, 0xe6, 0x2c, 0x9c, 0x26, 0xe3, 0x1d, 0xe5, 0x2f, 0x59,
	0x83, 0xfc, 0x1a, 0xc0, 0x66, 0xe6, 0x35, 0xad, 0x54, 0x89, 0x1f, 0xe2, 0xff, 0x9c, 0x85, 0xc3,
	0x64, 0xda, 0x4d, 0x9e, 0xba, 0x01, 0x7f, 0x86, 0x59, 0x89, 0x32, 0x6b, 0x6b, 0x9b, 0x1a, 0x34,
	0xa6, 0x22, 0x95, 0xfa, 0x0b, 0xc4, 0xc0, 0x45, 0x5f, 0xfe, 0x89, 0x76, 0x64, 0xdd, 0x55, 0x4e,
	0x2e, 0x0e, 0xb2, 0x8d, 0x57, 0x79, 0xc4, 0x03, 0x98, 0xb8, 0x8b, 0x0a, 0xaa, 0xc5, 0xd0, 0x15,
	0xf9, 0xf9, 0xe7, 0x1c, 0x06, 0x7b, 0xd2, 0x56, 0x8c, 0x5c, 0x07, 0xf7, 0xbd, 0x8c, 0x21, 0x20,
	0xbd, 0xfd, 0x9d, 0x51, 0x56, 0xc6, 0xea, 0x56, 0xd9, 0xaa, 0xc1, 0xe5, 0xb9, 0x7f, 0x13, 0x17,
	0x68, 0xd6, 0xec, 0x8b, 0xb1, 0x7c, 0xe4, 0xec, 0x1e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x66,
	0x47, 0xfd, 0x48, 0xbf, 0x01, 0x00, 0x00,
}
