// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/smoug25/tensorflow_serving_helper/tensorflow/core/framework/log_memory.proto

package framework

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MemoryLogStep struct {
	// Process-unique step id.
	StepId int64 `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Handle describing the feeds and fetches of the step.
	Handle               string   `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryLogStep) Reset()         { *m = MemoryLogStep{} }
func (m *MemoryLogStep) String() string { return proto.CompactTextString(m) }
func (*MemoryLogStep) ProtoMessage()    {}
func (*MemoryLogStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3184dee3a7249f7, []int{0}
}

func (m *MemoryLogStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryLogStep.Unmarshal(m, b)
}
func (m *MemoryLogStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryLogStep.Marshal(b, m, deterministic)
}
func (m *MemoryLogStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryLogStep.Merge(m, src)
}
func (m *MemoryLogStep) XXX_Size() int {
	return xxx_messageInfo_MemoryLogStep.Size(m)
}
func (m *MemoryLogStep) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryLogStep.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryLogStep proto.InternalMessageInfo

func (m *MemoryLogStep) GetStepId() int64 {
	if m != nil {
		return m.StepId
	}
	return 0
}

func (m *MemoryLogStep) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

type MemoryLogTensorAllocation struct {
	// Process-unique step id.
	StepId int64 `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Name of the kernel making the allocation as set in GraphDef,
	// e.g., "affine2/weights/Assign".
	KernelName string `protobuf:"bytes,2,opt,name=kernel_name,json=kernelName,proto3" json:"kernel_name,omitempty"`
	// Allocated tensor details.
	Tensor               *TensorDescription `protobuf:"bytes,3,opt,name=tensor,proto3" json:"tensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MemoryLogTensorAllocation) Reset()         { *m = MemoryLogTensorAllocation{} }
func (m *MemoryLogTensorAllocation) String() string { return proto.CompactTextString(m) }
func (*MemoryLogTensorAllocation) ProtoMessage()    {}
func (*MemoryLogTensorAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3184dee3a7249f7, []int{1}
}

func (m *MemoryLogTensorAllocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryLogTensorAllocation.Unmarshal(m, b)
}
func (m *MemoryLogTensorAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryLogTensorAllocation.Marshal(b, m, deterministic)
}
func (m *MemoryLogTensorAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryLogTensorAllocation.Merge(m, src)
}
func (m *MemoryLogTensorAllocation) XXX_Size() int {
	return xxx_messageInfo_MemoryLogTensorAllocation.Size(m)
}
func (m *MemoryLogTensorAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryLogTensorAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryLogTensorAllocation proto.InternalMessageInfo

func (m *MemoryLogTensorAllocation) GetStepId() int64 {
	if m != nil {
		return m.StepId
	}
	return 0
}

func (m *MemoryLogTensorAllocation) GetKernelName() string {
	if m != nil {
		return m.KernelName
	}
	return ""
}

func (m *MemoryLogTensorAllocation) GetTensor() *TensorDescription {
	if m != nil {
		return m.Tensor
	}
	return nil
}

type MemoryLogTensorDeallocation struct {
	// Id of the tensor buffer being deallocated, used to match to a
	// corresponding allocation.
	AllocationId int64 `protobuf:"varint,1,opt,name=allocation_id,json=allocationId,proto3" json:"allocation_id,omitempty"`
	// Name of the allocator used.
	AllocatorName        string   `protobuf:"bytes,2,opt,name=allocator_name,json=allocatorName,proto3" json:"allocator_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryLogTensorDeallocation) Reset()         { *m = MemoryLogTensorDeallocation{} }
func (m *MemoryLogTensorDeallocation) String() string { return proto.CompactTextString(m) }
func (*MemoryLogTensorDeallocation) ProtoMessage()    {}
func (*MemoryLogTensorDeallocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3184dee3a7249f7, []int{2}
}

func (m *MemoryLogTensorDeallocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryLogTensorDeallocation.Unmarshal(m, b)
}
func (m *MemoryLogTensorDeallocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryLogTensorDeallocation.Marshal(b, m, deterministic)
}
func (m *MemoryLogTensorDeallocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryLogTensorDeallocation.Merge(m, src)
}
func (m *MemoryLogTensorDeallocation) XXX_Size() int {
	return xxx_messageInfo_MemoryLogTensorDeallocation.Size(m)
}
func (m *MemoryLogTensorDeallocation) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryLogTensorDeallocation.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryLogTensorDeallocation proto.InternalMessageInfo

func (m *MemoryLogTensorDeallocation) GetAllocationId() int64 {
	if m != nil {
		return m.AllocationId
	}
	return 0
}

func (m *MemoryLogTensorDeallocation) GetAllocatorName() string {
	if m != nil {
		return m.AllocatorName
	}
	return ""
}

type MemoryLogTensorOutput struct {
	// Process-unique step id.
	StepId int64 `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Name of the kernel producing an output as set in GraphDef, e.g.,
	// "affine2/weights/Assign".
	KernelName string `protobuf:"bytes,2,opt,name=kernel_name,json=kernelName,proto3" json:"kernel_name,omitempty"`
	// Index of the output being set.
	Index int32 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	// Output tensor details.
	Tensor               *TensorDescription `protobuf:"bytes,4,opt,name=tensor,proto3" json:"tensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MemoryLogTensorOutput) Reset()         { *m = MemoryLogTensorOutput{} }
func (m *MemoryLogTensorOutput) String() string { return proto.CompactTextString(m) }
func (*MemoryLogTensorOutput) ProtoMessage()    {}
func (*MemoryLogTensorOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3184dee3a7249f7, []int{3}
}

func (m *MemoryLogTensorOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryLogTensorOutput.Unmarshal(m, b)
}
func (m *MemoryLogTensorOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryLogTensorOutput.Marshal(b, m, deterministic)
}
func (m *MemoryLogTensorOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryLogTensorOutput.Merge(m, src)
}
func (m *MemoryLogTensorOutput) XXX_Size() int {
	return xxx_messageInfo_MemoryLogTensorOutput.Size(m)
}
func (m *MemoryLogTensorOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryLogTensorOutput.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryLogTensorOutput proto.InternalMessageInfo

func (m *MemoryLogTensorOutput) GetStepId() int64 {
	if m != nil {
		return m.StepId
	}
	return 0
}

func (m *MemoryLogTensorOutput) GetKernelName() string {
	if m != nil {
		return m.KernelName
	}
	return ""
}

func (m *MemoryLogTensorOutput) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MemoryLogTensorOutput) GetTensor() *TensorDescription {
	if m != nil {
		return m.Tensor
	}
	return nil
}

type MemoryLogRawAllocation struct {
	// Process-unique step id.
	StepId int64 `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Name of the operation making the allocation.
	Operation string `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	// Number of bytes in the allocation.
	NumBytes int64 `protobuf:"varint,3,opt,name=num_bytes,json=numBytes,proto3" json:"num_bytes,omitempty"`
	// Address of the allocation.
	Ptr uint64 `protobuf:"varint,4,opt,name=ptr,proto3" json:"ptr,omitempty"`
	// Id of the tensor buffer being allocated, used to match to a
	// corresponding deallocation.
	AllocationId int64 `protobuf:"varint,5,opt,name=allocation_id,json=allocationId,proto3" json:"allocation_id,omitempty"`
	// Name of the allocator used.
	AllocatorName        string   `protobuf:"bytes,6,opt,name=allocator_name,json=allocatorName,proto3" json:"allocator_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryLogRawAllocation) Reset()         { *m = MemoryLogRawAllocation{} }
func (m *MemoryLogRawAllocation) String() string { return proto.CompactTextString(m) }
func (*MemoryLogRawAllocation) ProtoMessage()    {}
func (*MemoryLogRawAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3184dee3a7249f7, []int{4}
}

func (m *MemoryLogRawAllocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryLogRawAllocation.Unmarshal(m, b)
}
func (m *MemoryLogRawAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryLogRawAllocation.Marshal(b, m, deterministic)
}
func (m *MemoryLogRawAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryLogRawAllocation.Merge(m, src)
}
func (m *MemoryLogRawAllocation) XXX_Size() int {
	return xxx_messageInfo_MemoryLogRawAllocation.Size(m)
}
func (m *MemoryLogRawAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryLogRawAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryLogRawAllocation proto.InternalMessageInfo

func (m *MemoryLogRawAllocation) GetStepId() int64 {
	if m != nil {
		return m.StepId
	}
	return 0
}

func (m *MemoryLogRawAllocation) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *MemoryLogRawAllocation) GetNumBytes() int64 {
	if m != nil {
		return m.NumBytes
	}
	return 0
}

func (m *MemoryLogRawAllocation) GetPtr() uint64 {
	if m != nil {
		return m.Ptr
	}
	return 0
}

func (m *MemoryLogRawAllocation) GetAllocationId() int64 {
	if m != nil {
		return m.AllocationId
	}
	return 0
}

func (m *MemoryLogRawAllocation) GetAllocatorName() string {
	if m != nil {
		return m.AllocatorName
	}
	return ""
}

type MemoryLogRawDeallocation struct {
	// Process-unique step id.
	StepId int64 `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Name of the operation making the deallocation.
	Operation string `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	// Id of the tensor buffer being deallocated, used to match to a
	// corresponding allocation.
	AllocationId int64 `protobuf:"varint,3,opt,name=allocation_id,json=allocationId,proto3" json:"allocation_id,omitempty"`
	// Name of the allocator used.
	AllocatorName string `protobuf:"bytes,4,opt,name=allocator_name,json=allocatorName,proto3" json:"allocator_name,omitempty"`
	// True if the deallocation is queued and will be performed later,
	// e.g. for GPU lazy freeing of buffers.
	Deferred             bool     `protobuf:"varint,5,opt,name=deferred,proto3" json:"deferred,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryLogRawDeallocation) Reset()         { *m = MemoryLogRawDeallocation{} }
func (m *MemoryLogRawDeallocation) String() string { return proto.CompactTextString(m) }
func (*MemoryLogRawDeallocation) ProtoMessage()    {}
func (*MemoryLogRawDeallocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3184dee3a7249f7, []int{5}
}

func (m *MemoryLogRawDeallocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryLogRawDeallocation.Unmarshal(m, b)
}
func (m *MemoryLogRawDeallocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryLogRawDeallocation.Marshal(b, m, deterministic)
}
func (m *MemoryLogRawDeallocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryLogRawDeallocation.Merge(m, src)
}
func (m *MemoryLogRawDeallocation) XXX_Size() int {
	return xxx_messageInfo_MemoryLogRawDeallocation.Size(m)
}
func (m *MemoryLogRawDeallocation) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryLogRawDeallocation.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryLogRawDeallocation proto.InternalMessageInfo

func (m *MemoryLogRawDeallocation) GetStepId() int64 {
	if m != nil {
		return m.StepId
	}
	return 0
}

func (m *MemoryLogRawDeallocation) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *MemoryLogRawDeallocation) GetAllocationId() int64 {
	if m != nil {
		return m.AllocationId
	}
	return 0
}

func (m *MemoryLogRawDeallocation) GetAllocatorName() string {
	if m != nil {
		return m.AllocatorName
	}
	return ""
}

func (m *MemoryLogRawDeallocation) GetDeferred() bool {
	if m != nil {
		return m.Deferred
	}
	return false
}

func init() {
	proto.RegisterType((*MemoryLogStep)(nil), "tensorflow.MemoryLogStep")
	proto.RegisterType((*MemoryLogTensorAllocation)(nil), "tensorflow.MemoryLogTensorAllocation")
	proto.RegisterType((*MemoryLogTensorDeallocation)(nil), "tensorflow.MemoryLogTensorDeallocation")
	proto.RegisterType((*MemoryLogTensorOutput)(nil), "tensorflow.MemoryLogTensorOutput")
	proto.RegisterType((*MemoryLogRawAllocation)(nil), "tensorflow.MemoryLogRawAllocation")
	proto.RegisterType((*MemoryLogRawDeallocation)(nil), "tensorflow.MemoryLogRawDeallocation")
}

func init() {
	proto.RegisterFile("github.com/smoug25/tensorflow_serving_helper/tensorflow/core/framework/log_memory.proto", fileDescriptor_d3184dee3a7249f7)
}

var fileDescriptor_d3184dee3a7249f7 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x86, 0x19, 0xd3, 0xc6, 0xf6, 0xac, 0x55, 0x09, 0xba, 0xc6, 0x5d, 0xc5, 0x52, 0x11, 0x7a,
	0xd5, 0xc0, 0xca, 0xde, 0x6b, 0x59, 0x84, 0x85, 0x55, 0x97, 0x28, 0x08, 0xde, 0x84, 0xb4, 0x39,
	0x4d, 0xc3, 0x66, 0xe6, 0x0c, 0x93, 0x89, 0xdd, 0x7d, 0x07, 0x9f, 0xc1, 0xf7, 0xf0, 0x15, 0x7c,
	0x22, 0x2f, 0x25, 0x99, 0x9a, 0x89, 0xbb, 0x2b, 0x54, 0xb7, 0x77, 0xf9, 0x4f, 0x86, 0xf3, 0x7f,
	0xff, 0x39, 0x1c, 0xf8, 0x94, 0x66, 0x7a, 0x59, 0xce, 0x26, 0x73, 0xe2, 0x41, 0xc1, 0xa9, 0x4c,
	0x0f, 0x0e, 0x03, 0x8d, 0xa2, 0x20, 0xb5, 0xc8, 0x69, 0x15, 0x15, 0xa8, 0xbe, 0x64, 0x22, 0x8d,
	0x96, 0x98, 0x4b, 0x54, 0xad, 0x3f, 0xc1, 0x9c, 0x14, 0x06, 0x0b, 0x15, 0x73, 0x5c, 0x91, 0x3a,
	0x0b, 0x72, 0x4a, 0x23, 0x8e, 0x9c, 0xd4, 0xc5, 0x44, 0x2a, 0xd2, 0xe4, 0x81, 0x7d, 0xbb, 0x17,
	0x6d, 0xc9, 0xc4, 0xfc, 0x89, 0x12, 0x2c, 0xe6, 0x2a, 0x93, 0x3a, 0x23, 0x61, 0xcc, 0x46, 0xaf,
	0x60, 0xf0, 0xb6, 0x36, 0x3f, 0xa1, 0xf4, 0x83, 0x46, 0xe9, 0x3d, 0x82, 0xdb, 0x85, 0x46, 0x19,
	0x65, 0x89, 0xcf, 0x86, 0x6c, 0xec, 0x84, 0x6e, 0x25, 0x8f, 0x13, 0x6f, 0x17, 0xdc, 0x65, 0x2c,
	0x92, 0x1c, 0xfd, 0x5b, 0x43, 0x36, 0xee, 0x87, 0x6b, 0x35, 0xfa, 0xca, 0xe0, 0x71, 0xd3, 0xe2,
	0x63, 0xed, 0xf3, 0x3a, 0xcf, 0x69, 0x1e, 0x57, 0x2e, 0x7f, 0x6f, 0xf7, 0x0c, 0x76, 0xce, 0x50,
	0x09, 0xcc, 0x23, 0x11, 0xf3, 0xdf, 0x3d, 0xc1, 0x94, 0xde, 0xc5, 0x1c, 0xbd, 0x43, 0x70, 0x0d,
	0xb5, 0xef, 0x0c, 0xd9, 0x78, 0xe7, 0xe0, 0xe9, 0xc4, 0xc6, 0x9b, 0x18, 0x9f, 0x23, 0x1b, 0x27,
	0x5c, 0x3f, 0x1e, 0x65, 0xb0, 0x7f, 0x89, 0xe6, 0x08, 0x63, 0xcb, 0xf3, 0x1c, 0x06, 0x56, 0x59,
	0xaa, 0x3b, 0xb6, 0x78, 0x9c, 0x78, 0x2f, 0xe0, 0xee, 0x5a, 0x93, 0x6a, 0xe3, 0x0d, 0x9a, 0x6a,
	0x45, 0x38, 0xfa, 0xc6, 0xe0, 0xe1, 0x25, 0xaf, 0xf7, 0xa5, 0x96, 0xa5, 0xbe, 0x41, 0xea, 0x07,
	0xd0, 0xcd, 0x44, 0x82, 0xe7, 0x75, 0xe8, 0x6e, 0x68, 0x44, 0x6b, 0x16, 0x9d, 0x7f, 0x99, 0xc5,
	0x0f, 0x06, 0xbb, 0x0d, 0x60, 0x18, 0xaf, 0x36, 0xd9, 0xcb, 0x13, 0xe8, 0x93, 0x44, 0x55, 0xbf,
	0x5a, 0xf3, 0xd9, 0x82, 0xb7, 0x0f, 0x7d, 0x51, 0xf2, 0x68, 0x76, 0xa1, 0xb1, 0xa8, 0x11, 0x9d,
	0xb0, 0x27, 0x4a, 0x3e, 0xad, 0xb4, 0x77, 0x1f, 0x1c, 0xa9, 0x0d, 0x62, 0x27, 0xac, 0x3e, 0xaf,
	0x4e, 0xbb, 0xbb, 0xd1, 0xb4, 0xdd, 0xeb, 0xa6, 0xfd, 0x9d, 0x81, 0xdf, 0x0e, 0xf3, 0xc7, 0x5a,
	0xff, 0x33, 0xce, 0x15, 0x3e, 0x67, 0x23, 0xbe, 0xce, 0x35, 0x7c, 0xde, 0x1e, 0xf4, 0x12, 0x5c,
	0xa0, 0x52, 0x68, 0x62, 0xf6, 0xc2, 0x46, 0x4f, 0xcf, 0xc1, 0x27, 0x95, 0xb6, 0x97, 0xd6, 0x9c,
	0xe6, 0xf4, 0xde, 0x09, 0xa5, 0x26, 0xd7, 0x69, 0x75, 0x91, 0xc5, 0x29, 0xfb, 0xfc, 0x66, 0x3b,
	0x57, 0xff, 0x93, 0xb1, 0x99, 0x5b, 0x9f, 0xf9, 0xcb, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x21,
	0xac, 0x16, 0x82, 0xae, 0x04, 0x00, 0x00,
}
