// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/smoug25/tensorflow_serving_helper/tensorflow/core/framework/tensor_slice.proto

package tensorflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Can only be interpreted if you know the corresponding TensorShape.
type TensorSliceProto struct {
	// Extent of the slice in all tensor dimensions.
	//
	// Must have one entry for each of the dimension of the tensor that this
	// slice belongs to.  The order of sizes is the same as the order of
	// dimensions in the TensorShape.
	Extent               []*TensorSliceProto_Extent `protobuf:"bytes,1,rep,name=extent,proto3" json:"extent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TensorSliceProto) Reset()         { *m = TensorSliceProto{} }
func (m *TensorSliceProto) String() string { return proto.CompactTextString(m) }
func (*TensorSliceProto) ProtoMessage()    {}
func (*TensorSliceProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9681dcb4d945dbc6, []int{0}
}

func (m *TensorSliceProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TensorSliceProto.Unmarshal(m, b)
}
func (m *TensorSliceProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TensorSliceProto.Marshal(b, m, deterministic)
}
func (m *TensorSliceProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TensorSliceProto.Merge(m, src)
}
func (m *TensorSliceProto) XXX_Size() int {
	return xxx_messageInfo_TensorSliceProto.Size(m)
}
func (m *TensorSliceProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TensorSliceProto.DiscardUnknown(m)
}

var xxx_messageInfo_TensorSliceProto proto.InternalMessageInfo

func (m *TensorSliceProto) GetExtent() []*TensorSliceProto_Extent {
	if m != nil {
		return m.Extent
	}
	return nil
}

// Extent of the slice in one dimension.
type TensorSliceProto_Extent struct {
	// Start index of the slice, starting at 0.
	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	// Length of the slice: if the length is missing or -1 we will
	// interpret this as "everything in this dimension".  We use
	// "oneof" to preserve information about whether the length is
	// present without changing the serialization format from the
	// prior proto2 version of this proto.
	//
	// Types that are valid to be assigned to HasLength:
	//	*TensorSliceProto_Extent_Length
	HasLength            isTensorSliceProto_Extent_HasLength `protobuf_oneof:"has_length"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *TensorSliceProto_Extent) Reset()         { *m = TensorSliceProto_Extent{} }
func (m *TensorSliceProto_Extent) String() string { return proto.CompactTextString(m) }
func (*TensorSliceProto_Extent) ProtoMessage()    {}
func (*TensorSliceProto_Extent) Descriptor() ([]byte, []int) {
	return fileDescriptor_9681dcb4d945dbc6, []int{0, 0}
}

func (m *TensorSliceProto_Extent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TensorSliceProto_Extent.Unmarshal(m, b)
}
func (m *TensorSliceProto_Extent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TensorSliceProto_Extent.Marshal(b, m, deterministic)
}
func (m *TensorSliceProto_Extent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TensorSliceProto_Extent.Merge(m, src)
}
func (m *TensorSliceProto_Extent) XXX_Size() int {
	return xxx_messageInfo_TensorSliceProto_Extent.Size(m)
}
func (m *TensorSliceProto_Extent) XXX_DiscardUnknown() {
	xxx_messageInfo_TensorSliceProto_Extent.DiscardUnknown(m)
}

var xxx_messageInfo_TensorSliceProto_Extent proto.InternalMessageInfo

func (m *TensorSliceProto_Extent) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

type isTensorSliceProto_Extent_HasLength interface {
	isTensorSliceProto_Extent_HasLength()
}

type TensorSliceProto_Extent_Length struct {
	Length int64 `protobuf:"varint,2,opt,name=length,proto3,oneof"`
}

func (*TensorSliceProto_Extent_Length) isTensorSliceProto_Extent_HasLength() {}

func (m *TensorSliceProto_Extent) GetHasLength() isTensorSliceProto_Extent_HasLength {
	if m != nil {
		return m.HasLength
	}
	return nil
}

func (m *TensorSliceProto_Extent) GetLength() int64 {
	if x, ok := m.GetHasLength().(*TensorSliceProto_Extent_Length); ok {
		return x.Length
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TensorSliceProto_Extent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TensorSliceProto_Extent_Length)(nil),
	}
}

func init() {
	proto.RegisterType((*TensorSliceProto)(nil), "tensorflow.TensorSliceProto")
	proto.RegisterType((*TensorSliceProto_Extent)(nil), "tensorflow.TensorSliceProto.Extent")
}

func init() {
	proto.RegisterFile("github.com/smoug25/tensorflow_serving_helper/tensorflow/core/framework/tensor_slice.proto", fileDescriptor_9681dcb4d945dbc6)
}

var fileDescriptor_9681dcb4d945dbc6 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x31, 0x15, 0x19, 0x0e, 0x06, 0x88, 0x18, 0x22, 0x26, 0x04, 0x4b, 0x27, 0x5b, 0x0a,
	0x62, 0x62, 0xab, 0x04, 0x62, 0xac, 0x02, 0x0b, 0x93, 0x95, 0x46, 0x57, 0x3b, 0xc2, 0xf1, 0x55,
	0x67, 0x97, 0xf2, 0x26, 0xbc, 0x2a, 0x23, 0x8a, 0x6b, 0xd1, 0x2a, 0xe3, 0x77, 0xf7, 0xfd, 0xf6,
	0xfd, 0xf0, 0x61, 0xfa, 0x68, 0xb7, 0x2b, 0xd9, 0xd1, 0xa0, 0xc2, 0x40, 0x5b, 0x53, 0x3f, 0xaa,
	0x88, 0x3e, 0x10, 0xaf, 0x1d, 0xed, 0x74, 0x40, 0xfe, 0xea, 0xbd, 0xd1, 0x16, 0xdd, 0x06, 0xf9,
	0x68, 0xa3, 0x3a, 0x62, 0x54, 0x6b, 0x6e, 0x07, 0xdc, 0x11, 0x7f, 0xe6, 0x8d, 0x0e, 0xae, 0xef,
	0x50, 0x6e, 0x98, 0x22, 0x95, 0x70, 0xb0, 0xef, 0x7e, 0x04, 0x5c, 0xbe, 0x27, 0x7c, 0x1b, 0x8d,
	0x65, 0x12, 0x9e, 0xa0, 0xc0, 0xef, 0x88, 0x3e, 0x56, 0xe2, 0x76, 0x36, 0x3f, 0xaf, 0xef, 0xe5,
	0x21, 0x21, 0xa7, 0xb6, 0x7c, 0x4e, 0x6a, 0x93, 0x23, 0x37, 0x2f, 0x50, 0xec, 0x27, 0xe5, 0x35,
	0x9c, 0x85, 0xd8, 0xf2, 0xf8, 0x8a, 0x98, 0xcf, 0x9a, 0x3d, 0x94, 0x15, 0x14, 0x0e, 0xbd, 0x89,
	0xb6, 0x3a, 0x1d, 0xc7, 0xaf, 0x27, 0x4d, 0xe6, 0xc5, 0x05, 0x80, 0x6d, 0x83, 0xce, 0x54, 0x43,
	0x45, 0x6c, 0x8e, 0x7f, 0xfe, 0x2f, 0xb5, 0xb8, 0x9a, 0x1e, 0x11, 0x96, 0xe2, 0x57, 0x88, 0x55,
	0x91, 0x0a, 0x3e, 0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x87, 0x8f, 0xae, 0x3d, 0x01, 0x00,
	0x00,
}
