// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/smoug25/tensorflow_serving_helper/tensorflow_serving/sources/storage_path/static_storage_path_source.proto

package storage_path

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Config proto for StaticStoragePathSource.
type StaticStoragePathSourceConfig struct {
	// The single servable name, version number and path to supply statically.
	ServableName         string   `protobuf:"bytes,1,opt,name=servable_name,json=servableName,proto3" json:"servable_name,omitempty"`
	VersionNum           int64    `protobuf:"varint,2,opt,name=version_num,json=versionNum,proto3" json:"version_num,omitempty"`
	VersionPath          string   `protobuf:"bytes,3,opt,name=version_path,json=versionPath,proto3" json:"version_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticStoragePathSourceConfig) Reset()         { *m = StaticStoragePathSourceConfig{} }
func (m *StaticStoragePathSourceConfig) String() string { return proto.CompactTextString(m) }
func (*StaticStoragePathSourceConfig) ProtoMessage()    {}
func (*StaticStoragePathSourceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_55fb45acb8167463, []int{0}
}

func (m *StaticStoragePathSourceConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticStoragePathSourceConfig.Unmarshal(m, b)
}
func (m *StaticStoragePathSourceConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticStoragePathSourceConfig.Marshal(b, m, deterministic)
}
func (m *StaticStoragePathSourceConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticStoragePathSourceConfig.Merge(m, src)
}
func (m *StaticStoragePathSourceConfig) XXX_Size() int {
	return xxx_messageInfo_StaticStoragePathSourceConfig.Size(m)
}
func (m *StaticStoragePathSourceConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticStoragePathSourceConfig.DiscardUnknown(m)
}

var xxx_messageInfo_StaticStoragePathSourceConfig proto.InternalMessageInfo

func (m *StaticStoragePathSourceConfig) GetServableName() string {
	if m != nil {
		return m.ServableName
	}
	return ""
}

func (m *StaticStoragePathSourceConfig) GetVersionNum() int64 {
	if m != nil {
		return m.VersionNum
	}
	return 0
}

func (m *StaticStoragePathSourceConfig) GetVersionPath() string {
	if m != nil {
		return m.VersionPath
	}
	return ""
}

func init() {
	proto.RegisterType((*StaticStoragePathSourceConfig)(nil), "tensorflow.serving.StaticStoragePathSourceConfig")
}

func init() {
	proto.RegisterFile("github.com/smoug25/tensorflow_serving_helper/tensorflow_serving/sources/storage_path/static_storage_path_source.proto", fileDescriptor_55fb45acb8167463)
}

var fileDescriptor_55fb45acb8167463 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xa9, 0x0b, 0x82, 0x71, 0xbd, 0xe4, 0xd4, 0x8b, 0xb8, 0xea, 0x65, 0x4f, 0x0d, 0x28,
	0xfe, 0x01, 0xbd, 0x2f, 0xb2, 0xc5, 0x8b, 0x97, 0x90, 0x96, 0xd9, 0x24, 0xd0, 0x64, 0x4a, 0x66,
	0xb2, 0xfe, 0x05, 0x7f, 0xb6, 0x34, 0xdb, 0xa2, 0x82, 0x47, 0xaf, 0x6f, 0xde, 0xf7, 0x66, 0xe6,
	0x89, 0x6c, 0x3d, 0xbb, 0xdc, 0x35, 0x3d, 0x06, 0x45, 0x01, 0xb3, 0x7d, 0x78, 0x52, 0x0c, 0x91,
	0x30, 0x1d, 0x06, 0xfc, 0xd0, 0x04, 0xe9, 0xe8, 0xa3, 0xd5, 0x0e, 0x86, 0x11, 0xd2, 0x1f, 0x13,
	0x45, 0x98, 0x53, 0x0f, 0xa4, 0x88, 0x31, 0x19, 0x0b, 0x7a, 0x34, 0xec, 0x14, 0xb1, 0x61, 0xdf,
	0xeb, 0x9f, 0x9a, 0x3e, 0x19, 0x9b, 0x31, 0x21, 0xa3, 0x94, 0xdf, 0x49, 0xcd, 0x9c, 0x74, 0xf7,
	0x59, 0x89, 0xeb, 0xb6, 0x80, 0xed, 0x89, 0x7b, 0x35, 0xec, 0xda, 0x42, 0xbd, 0x60, 0x3c, 0x78,
	0x2b, 0xef, 0xc5, 0xd5, 0x64, 0x36, 0xdd, 0x00, 0x3a, 0x9a, 0x00, 0x75, 0xb5, 0xa9, 0xb6, 0x17,
	0xfb, 0xf5, 0x22, 0xee, 0x4c, 0x00, 0x79, 0x23, 0x2e, 0x8f, 0x90, 0xc8, 0x63, 0xd4, 0x31, 0x87,
	0xfa, 0x6c, 0x53, 0x6d, 0x57, 0x7b, 0x31, 0x4b, 0xbb, 0x1c, 0xe4, 0xad, 0x58, 0x2f, 0x86, 0xe9,
	0xb0, 0x7a, 0x55, 0x42, 0x16, 0x68, 0x5a, 0xfa, 0xfc, 0xf6, 0xde, 0xfe, 0x4f, 0x2f, 0xbf, 0x6a,
	0xe9, 0xce, 0xcb, 0xf3, 0x8f, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x8b, 0xf7, 0x1e, 0x75,
	0x01, 0x00, 0x00,
}
