// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/smoug25/tensorflow_serving_helper/tensorflow_serving/apis/get_model_metadata.proto

package apis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	protobuf "github.com/smoug25/tensorflow_serving_helper/tensorflow/core/protobuf"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message returned for "signature_def" field.
type SignatureDefMap struct {
	SignatureDef         map[string]*protobuf.SignatureDef `protobuf:"bytes,1,rep,name=signature_def,json=signatureDef,proto3" json:"signature_def,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SignatureDefMap) Reset()         { *m = SignatureDefMap{} }
func (m *SignatureDefMap) String() string { return proto.CompactTextString(m) }
func (*SignatureDefMap) ProtoMessage()    {}
func (*SignatureDefMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3c1baa95e3cb56, []int{0}
}

func (m *SignatureDefMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureDefMap.Unmarshal(m, b)
}
func (m *SignatureDefMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureDefMap.Marshal(b, m, deterministic)
}
func (m *SignatureDefMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureDefMap.Merge(m, src)
}
func (m *SignatureDefMap) XXX_Size() int {
	return xxx_messageInfo_SignatureDefMap.Size(m)
}
func (m *SignatureDefMap) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureDefMap.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureDefMap proto.InternalMessageInfo

func (m *SignatureDefMap) GetSignatureDef() map[string]*protobuf.SignatureDef {
	if m != nil {
		return m.SignatureDef
	}
	return nil
}

type GetModelMetadataRequest struct {
	// Model Specification indicating which model we are querying for metadata.
	// If version is not specified, will use the latest (numerical) version.
	ModelSpec *ModelSpec `protobuf:"bytes,1,opt,name=model_spec,json=modelSpec,proto3" json:"model_spec,omitempty"`
	// Metadata fields to get. Currently supported: "signature_def".
	MetadataField        []string `protobuf:"bytes,2,rep,name=metadata_field,json=metadataField,proto3" json:"metadata_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetModelMetadataRequest) Reset()         { *m = GetModelMetadataRequest{} }
func (m *GetModelMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*GetModelMetadataRequest) ProtoMessage()    {}
func (*GetModelMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3c1baa95e3cb56, []int{1}
}

func (m *GetModelMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetModelMetadataRequest.Unmarshal(m, b)
}
func (m *GetModelMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetModelMetadataRequest.Marshal(b, m, deterministic)
}
func (m *GetModelMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetModelMetadataRequest.Merge(m, src)
}
func (m *GetModelMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_GetModelMetadataRequest.Size(m)
}
func (m *GetModelMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetModelMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetModelMetadataRequest proto.InternalMessageInfo

func (m *GetModelMetadataRequest) GetModelSpec() *ModelSpec {
	if m != nil {
		return m.ModelSpec
	}
	return nil
}

func (m *GetModelMetadataRequest) GetMetadataField() []string {
	if m != nil {
		return m.MetadataField
	}
	return nil
}

type GetModelMetadataResponse struct {
	// Model Specification indicating which model this metadata belongs to.
	ModelSpec *ModelSpec `protobuf:"bytes,1,opt,name=model_spec,json=modelSpec,proto3" json:"model_spec,omitempty"`
	// Map of metadata field name to metadata field. The options for metadata
	// field name are listed in GetModelMetadataRequest. Currently supported:
	// "signature_def".
	Metadata             map[string]*any.Any `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetModelMetadataResponse) Reset()         { *m = GetModelMetadataResponse{} }
func (m *GetModelMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*GetModelMetadataResponse) ProtoMessage()    {}
func (*GetModelMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da3c1baa95e3cb56, []int{2}
}

func (m *GetModelMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetModelMetadataResponse.Unmarshal(m, b)
}
func (m *GetModelMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetModelMetadataResponse.Marshal(b, m, deterministic)
}
func (m *GetModelMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetModelMetadataResponse.Merge(m, src)
}
func (m *GetModelMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_GetModelMetadataResponse.Size(m)
}
func (m *GetModelMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetModelMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetModelMetadataResponse proto.InternalMessageInfo

func (m *GetModelMetadataResponse) GetModelSpec() *ModelSpec {
	if m != nil {
		return m.ModelSpec
	}
	return nil
}

func (m *GetModelMetadataResponse) GetMetadata() map[string]*any.Any {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*SignatureDefMap)(nil), "tensorflow.serving.SignatureDefMap")
	proto.RegisterMapType((map[string]*protobuf.SignatureDef)(nil), "tensorflow.serving.SignatureDefMap.SignatureDefEntry")
	proto.RegisterType((*GetModelMetadataRequest)(nil), "tensorflow.serving.GetModelMetadataRequest")
	proto.RegisterType((*GetModelMetadataResponse)(nil), "tensorflow.serving.GetModelMetadataResponse")
	proto.RegisterMapType((map[string]*any.Any)(nil), "tensorflow.serving.GetModelMetadataResponse.MetadataEntry")
}

func init() {
	proto.RegisterFile("github.com/smoug25/tensorflow_serving_helper/tensorflow_serving/apis/get_model_metadata.proto", fileDescriptor_da3c1baa95e3cb56)
}

var fileDescriptor_da3c1baa95e3cb56 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4f, 0xeb, 0xd3, 0x40,
	0x10, 0x65, 0x53, 0x14, 0xbb, 0xb1, 0xfe, 0x09, 0x82, 0x31, 0x20, 0x84, 0x82, 0x10, 0x3c, 0x6c,
	0x20, 0xf2, 0x03, 0x29, 0x5e, 0x94, 0xaa, 0x78, 0x28, 0x68, 0x0a, 0x05, 0x0b, 0x12, 0xb6, 0xc9,
	0x64, 0x1b, 0x4c, 0xb2, 0xeb, 0xee, 0xa6, 0x92, 0x8b, 0x17, 0xbf, 0x9c, 0x1f, 0xc9, 0xa3, 0x24,
	0x69, 0x34, 0xb5, 0xf1, 0xe2, 0xaf, 0xb7, 0xcd, 0x9b, 0x79, 0xf3, 0x66, 0xf2, 0x1e, 0xfe, 0xc4,
	0x32, 0xbd, 0xaf, 0x76, 0x24, 0xe6, 0x85, 0xaf, 0x0a, 0x5e, 0xb1, 0xe0, 0xca, 0xd7, 0x50, 0x2a,
	0x2e, 0xd3, 0x9c, 0x7f, 0x8d, 0x14, 0xc8, 0x43, 0x56, 0xb2, 0x68, 0x0f, 0xb9, 0x00, 0x39, 0x52,
	0xf1, 0xa9, 0xc8, 0x94, 0xcf, 0x40, 0x47, 0x05, 0x4f, 0x20, 0x8f, 0x0a, 0xd0, 0x34, 0xa1, 0x9a,
	0x12, 0x21, 0xb9, 0xe6, 0x96, 0xf5, 0x87, 0x41, 0x8e, 0x0c, 0xe7, 0x11, 0xe3, 0x9c, 0xe5, 0xe0,
	0xb7, 0x1d, 0xbb, 0x2a, 0xf5, 0x69, 0x59, 0x77, 0xed, 0xce, 0xe6, 0x3f, 0xb7, 0xf1, 0x63, 0x2e,
	0x07, 0x03, 0x9b, 0x25, 0x22, 0x26, 0xa9, 0xd8, 0x1f, 0xe7, 0xbe, 0xbf, 0xc8, 0x95, 0xed, 0x85,
	0xdd, 0xc4, 0xf9, 0x0f, 0x84, 0xef, 0xae, 0x33, 0x56, 0x52, 0x5d, 0x49, 0x58, 0x42, 0xba, 0xa2,
	0xc2, 0xda, 0xe2, 0x99, 0xea, 0xa1, 0x28, 0x81, 0xd4, 0x46, 0xee, 0xc4, 0x33, 0x83, 0x2b, 0x72,
	0xfe, 0x13, 0xc8, 0x5f, 0xdc, 0x93, 0xef, 0xd7, 0xa5, 0x96, 0x75, 0x78, 0x5b, 0x0d, 0x20, 0xe7,
	0x23, 0xbe, 0x7f, 0xd6, 0x62, 0xdd, 0xc3, 0x93, 0xcf, 0x50, 0xdb, 0xc8, 0x45, 0xde, 0x34, 0x6c,
	0x9e, 0x16, 0xc1, 0x37, 0x0e, 0x34, 0xaf, 0xc0, 0x36, 0x5c, 0xe4, 0x99, 0x81, 0x3d, 0x94, 0x1e,
	0xf2, 0xc3, 0xae, 0x6d, 0x61, 0x3c, 0x47, 0xf3, 0x6f, 0xf8, 0xe1, 0x5b, 0xd0, 0xab, 0xe6, 0xb8,
	0xd5, 0xd1, 0xbd, 0x10, 0xbe, 0x54, 0xa0, 0xb4, 0xf5, 0x02, 0xe3, 0xce, 0x56, 0x25, 0x20, 0x6e,
	0x75, 0xcc, 0xe0, 0xf1, 0xd8, 0x39, 0x2d, 0x7b, 0x2d, 0x20, 0x0e, 0xa7, 0x45, 0xff, 0xb4, 0x9e,
	0xe0, 0x3b, 0x7d, 0x1c, 0xa2, 0x34, 0x83, 0x3c, 0xb1, 0x0d, 0x77, 0xe2, 0x4d, 0xc3, 0x59, 0x8f,
	0xbe, 0x69, 0xc0, 0xf9, 0x77, 0x03, 0xdb, 0xe7, 0x0b, 0x28, 0xc1, 0x4b, 0x05, 0xd7, 0xdc, 0x60,
	0x83, 0x6f, 0xf5, 0x5a, 0xad, 0xb6, 0x19, 0x2c, 0xc6, 0xb8, 0xff, 0x52, 0x27, 0x3d, 0xd0, 0x39,
	0xf2, 0x7b, 0x96, 0xf3, 0x01, 0xcf, 0x4e, 0x4a, 0x23, 0x4e, 0x3c, 0x3d, 0x75, 0xe2, 0x01, 0xe9,
	0x52, 0x4f, 0xfa, 0x90, 0x92, 0x97, 0x65, 0x3d, 0x70, 0xe1, 0xd5, 0xbb, 0xed, 0xf2, 0x12, 0x21,
	0xfd, 0x89, 0xd0, 0xee, 0x66, 0xab, 0xf1, 0xec, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0xbf,
	0x2b, 0xb4, 0xdc, 0x03, 0x00, 0x00,
}
