// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/smoug25/tensorflow_serving_helper/tensorflow_serving/apis/regression.proto

package apis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Regression result for a single item (tensorflow.Example).
type Regression struct {
	Value                float32  `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Regression) Reset()         { *m = Regression{} }
func (m *Regression) String() string { return proto.CompactTextString(m) }
func (*Regression) ProtoMessage()    {}
func (*Regression) Descriptor() ([]byte, []int) {
	return fileDescriptor_a86e996d77e36c50, []int{0}
}

func (m *Regression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Regression.Unmarshal(m, b)
}
func (m *Regression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Regression.Marshal(b, m, deterministic)
}
func (m *Regression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Regression.Merge(m, src)
}
func (m *Regression) XXX_Size() int {
	return xxx_messageInfo_Regression.Size(m)
}
func (m *Regression) XXX_DiscardUnknown() {
	xxx_messageInfo_Regression.DiscardUnknown(m)
}

var xxx_messageInfo_Regression proto.InternalMessageInfo

func (m *Regression) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// Contains one result per input example, in the same order as the input in
// RegressionRequest.
type RegressionResult struct {
	Regressions          []*Regression `protobuf:"bytes,1,rep,name=regressions,proto3" json:"regressions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RegressionResult) Reset()         { *m = RegressionResult{} }
func (m *RegressionResult) String() string { return proto.CompactTextString(m) }
func (*RegressionResult) ProtoMessage()    {}
func (*RegressionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a86e996d77e36c50, []int{1}
}

func (m *RegressionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegressionResult.Unmarshal(m, b)
}
func (m *RegressionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegressionResult.Marshal(b, m, deterministic)
}
func (m *RegressionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegressionResult.Merge(m, src)
}
func (m *RegressionResult) XXX_Size() int {
	return xxx_messageInfo_RegressionResult.Size(m)
}
func (m *RegressionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RegressionResult.DiscardUnknown(m)
}

var xxx_messageInfo_RegressionResult proto.InternalMessageInfo

func (m *RegressionResult) GetRegressions() []*Regression {
	if m != nil {
		return m.Regressions
	}
	return nil
}

type RegressionRequest struct {
	// Model Specification. If version is not specified, will use the latest
	// (numerical) version.
	ModelSpec *ModelSpec `protobuf:"bytes,1,opt,name=model_spec,json=modelSpec,proto3" json:"model_spec,omitempty"`
	// Input data.
	Input                *Input   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegressionRequest) Reset()         { *m = RegressionRequest{} }
func (m *RegressionRequest) String() string { return proto.CompactTextString(m) }
func (*RegressionRequest) ProtoMessage()    {}
func (*RegressionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a86e996d77e36c50, []int{2}
}

func (m *RegressionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegressionRequest.Unmarshal(m, b)
}
func (m *RegressionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegressionRequest.Marshal(b, m, deterministic)
}
func (m *RegressionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegressionRequest.Merge(m, src)
}
func (m *RegressionRequest) XXX_Size() int {
	return xxx_messageInfo_RegressionRequest.Size(m)
}
func (m *RegressionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegressionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegressionRequest proto.InternalMessageInfo

func (m *RegressionRequest) GetModelSpec() *ModelSpec {
	if m != nil {
		return m.ModelSpec
	}
	return nil
}

func (m *RegressionRequest) GetInput() *Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type RegressionResponse struct {
	// Effective Model Specification used for regression.
	ModelSpec            *ModelSpec        `protobuf:"bytes,2,opt,name=model_spec,json=modelSpec,proto3" json:"model_spec,omitempty"`
	Result               *RegressionResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RegressionResponse) Reset()         { *m = RegressionResponse{} }
func (m *RegressionResponse) String() string { return proto.CompactTextString(m) }
func (*RegressionResponse) ProtoMessage()    {}
func (*RegressionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a86e996d77e36c50, []int{3}
}

func (m *RegressionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegressionResponse.Unmarshal(m, b)
}
func (m *RegressionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegressionResponse.Marshal(b, m, deterministic)
}
func (m *RegressionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegressionResponse.Merge(m, src)
}
func (m *RegressionResponse) XXX_Size() int {
	return xxx_messageInfo_RegressionResponse.Size(m)
}
func (m *RegressionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegressionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegressionResponse proto.InternalMessageInfo

func (m *RegressionResponse) GetModelSpec() *ModelSpec {
	if m != nil {
		return m.ModelSpec
	}
	return nil
}

func (m *RegressionResponse) GetResult() *RegressionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Regression)(nil), "tensorflow.serving.Regression")
	proto.RegisterType((*RegressionResult)(nil), "tensorflow.serving.RegressionResult")
	proto.RegisterType((*RegressionRequest)(nil), "tensorflow.serving.RegressionRequest")
	proto.RegisterType((*RegressionResponse)(nil), "tensorflow.serving.RegressionResponse")
}

func init() {
	proto.RegisterFile("github.com/smoug25/tensorflow_serving_helper/tensorflow_serving/apis/regression.proto", fileDescriptor_a86e996d77e36c50)
}

var fileDescriptor_a86e996d77e36c50 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0xd9, 0x93, 0x3b, 0x70, 0xd2, 0xe8, 0x62, 0x11, 0x05, 0xe5, 0x08, 0x16, 0x57, 0x25,
	0x10, 0xb1, 0xbb, 0x42, 0xc4, 0xe6, 0x0a, 0x41, 0x56, 0x6d, 0x6c, 0xc2, 0x5d, 0x1c, 0x73, 0x81,
	0x24, 0xbb, 0xee, 0xec, 0x9e, 0xbd, 0xbf, 0xc0, 0x9f, 0x6b, 0x29, 0xb7, 0x89, 0x26, 0x6a, 0x40,
	0x84, 0x74, 0x09, 0xfb, 0xbd, 0x37, 0x6f, 0xde, 0xc0, 0x7d, 0x96, 0x9b, 0xb5, 0x5d, 0x85, 0xa9,
	0x2c, 0x23, 0x2a, 0xa5, 0xcd, 0xe2, 0xf3, 0xc8, 0x60, 0x45, 0x52, 0x3f, 0x15, 0xf2, 0x25, 0x21,
	0xd4, 0x9b, 0xbc, 0xca, 0x92, 0x35, 0x16, 0x0a, 0x75, 0xcf, 0x4b, 0xb4, 0x54, 0x39, 0x45, 0x1a,
	0x33, 0x8d, 0x44, 0xb9, 0xac, 0x42, 0xa5, 0xa5, 0x91, 0x9c, 0xb7, 0x64, 0xd8, 0x90, 0x47, 0x37,
	0x83, 0x8c, 0xca, 0x2b, 0x65, 0x4d, 0x3d, 0x65, 0x20, 0xc7, 0x52, 0x3e, 0x62, 0x51, 0x3b, 0x06,
	0x01, 0x80, 0xf8, 0xda, 0x85, 0x1f, 0xc0, 0x78, 0xb3, 0x2c, 0x2c, 0xfa, 0x6c, 0xca, 0x66, 0x23,
	0x51, 0xff, 0x04, 0x77, 0xb0, 0xd7, 0x32, 0x02, 0xc9, 0x16, 0x86, 0x5f, 0x80, 0xd7, 0x76, 0x40,
	0x3e, 0x9b, 0xee, 0xcc, 0xbc, 0xf8, 0x24, 0xfc, 0xdd, 0x42, 0xd8, 0x91, 0x76, 0x25, 0xc1, 0x2b,
	0x83, 0xfd, 0xae, 0xed, 0xb3, 0x45, 0x32, 0x7c, 0x0e, 0xe0, 0xe2, 0x25, 0xa4, 0x30, 0x75, 0x31,
	0xbc, 0xf8, 0xb8, 0xcf, 0xf6, 0x7a, 0x4b, 0xdd, 0x2a, 0x4c, 0xc5, 0x6e, 0xf9, 0xf9, 0xc9, 0x23,
	0x18, 0xbb, 0xba, 0xfc, 0x91, 0x13, 0x1e, 0xf6, 0x09, 0x17, 0x5b, 0x40, 0xd4, 0x5c, 0xf0, 0xc6,
	0x80, 0x7f, 0xdb, 0x4d, 0xc9, 0x8a, 0xf0, 0x47, 0x8a, 0xd1, 0x3f, 0x53, 0xcc, 0x61, 0xa2, 0x5d,
	0x4b, 0x4d, 0xfe, 0xd3, 0x3f, 0x6a, 0x71, 0xac, 0x68, 0x34, 0x97, 0x8b, 0x87, 0xab, 0x21, 0xae,
	0xfc, 0xce, 0xd8, 0x6a, 0xe2, 0x6e, 0x7c, 0xf6, 0x11, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x8a, 0xac,
	0xfb, 0xf4, 0x02, 0x00, 0x00,
}
